/**
 * PCC - Paulo C Compiler
 *
 * token/palavra-chave.h
 *
 * Paulo Tobias
 * paulohtobias@outlook.com
 */

#ifndef TOKEN_PALAVRA_CHAVE_H
#define TOKEN_PALAVRA_CHAVE_H

#include "token.h"

// TODO: x-macro pra cada KW
#define PALAVRA_CHAVE_SUBTIPOS \
	PALAVRA_CHAVE_SUBTIPO(TK_KW_AUTO, "auto") \
	PALAVRA_CHAVE_SUBTIPO(TK_KW_BREAK, "break") \
	PALAVRA_CHAVE_SUBTIPO(TK_KW_CASE, "case") \
	PALAVRA_CHAVE_SUBTIPO(TK_KW_CHAR, "char") \
	PALAVRA_CHAVE_SUBTIPO(TK_KW_CONST, "const") \
	PALAVRA_CHAVE_SUBTIPO(TK_KW_CONTINUE, "continue") \
	PALAVRA_CHAVE_SUBTIPO(TK_KW_DEFAULT, "default") \
	PALAVRA_CHAVE_SUBTIPO(TK_KW_DO, "do") \
	PALAVRA_CHAVE_SUBTIPO(TK_KW_DOUBLE, "double") \
	PALAVRA_CHAVE_SUBTIPO(TK_KW_ELSE, "else") \
	PALAVRA_CHAVE_SUBTIPO(TK_KW_ENUM, "enum") \
	PALAVRA_CHAVE_SUBTIPO(TK_KW_EXTERN, "extern") \
	PALAVRA_CHAVE_SUBTIPO(TK_KW_FLOAT, "float") \
	PALAVRA_CHAVE_SUBTIPO(TK_KW_FOR, "for") \
	PALAVRA_CHAVE_SUBTIPO(TK_KW_GOTO, "goto") \
	PALAVRA_CHAVE_SUBTIPO(TK_KW_IF, "if") \
	PALAVRA_CHAVE_SUBTIPO(TK_KW_INT, "int") \
	PALAVRA_CHAVE_SUBTIPO(TK_KW_LONG, "long") \
	PALAVRA_CHAVE_SUBTIPO(TK_KW_REGISTER, "register") \
	PALAVRA_CHAVE_SUBTIPO(TK_KW_RETURN, "return") \
	PALAVRA_CHAVE_SUBTIPO(TK_KW_SHORT, "short") \
	PALAVRA_CHAVE_SUBTIPO(TK_KW_SIGNED, "signed") \
	PALAVRA_CHAVE_SUBTIPO(TK_KW_SIZEOF, "sizeof") \
	PALAVRA_CHAVE_SUBTIPO(TK_KW_STATIC, "static") \
	PALAVRA_CHAVE_SUBTIPO(TK_KW_STRUCT, "struct") \
	PALAVRA_CHAVE_SUBTIPO(TK_KW_SWITCH, "switch") \
	PALAVRA_CHAVE_SUBTIPO(TK_KW_TYPEDEF, "typedef") \
	PALAVRA_CHAVE_SUBTIPO(TK_KW_UNION, "union") \
	PALAVRA_CHAVE_SUBTIPO(TK_KW_UNSIGNED, "unsigned") \
	PALAVRA_CHAVE_SUBTIPO(TK_KW_VOID, "void") \
	PALAVRA_CHAVE_SUBTIPO(TK_KW_VOLATILE, "volatile") \
	PALAVRA_CHAVE_SUBTIPO(TK_KW_WHILE, "while")

#define PALAVRA_CHAVE_SUBTIPO(cod, str) cod,
enum {
	PALAVRA_CHAVE_SUBTIPOS
};
#undef PALAVRA_CHAVE_SUBTIPO

int token_palavra_chave_init();

int token_palavra_chave_buscar(const token_t *token);

const char *token_palavra_chave_subtipo_str(uint32_t subtipo);

#endif // TOKEN_PALAVRA_CHAVE_H
